name: Vulnerability Scan
on:
  workflow_call:

jobs:
  cve:
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - name: Set up Golang
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      
      - name: Check CVEs using golvulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@v1.7.0 && govulncheck ./...
