name: Release Library
on:
  workflow_call:
    inputs:
      release-body:
        required: true
        type: string
      wait-for-checks:
        type: string

jobs:
  release:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - name: Wait for required checks
        uses: feronatech/shared-workflows/.github/actions/wait-for-checks-to-succeed@main
        if: ${{ inputs.wait-for-checks != '' }}
        with:
          list-of-checks: ${{ inputs.wait-for-checks }}

      - uses: actions/checkout@v7

      - name: Set up Golang
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Generate attestation
        uses: feronatech/shared-workflows/.github/actions/generate-go-attestation@main
        id: attestation

      - name: Release package
        uses: softprops/action-gh-release@v3
        with:
          body: ${{ inputs.release-body }}
          generate_release_notes: true
          make_latest: true
          files: |
            ${{ steps.attestation.outputs.manifest_path }}
            ${{ steps.attestation.outputs.attestation_path }}
