name: Release Library
on:
  workflow_call:
    inputs:
      release-body:
        required: true
        type: string
      wait-for-checks:
        type: string

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Wait for required checks
        uses: ./.github/actions/wait-for-checks-to-succeed
        if: ${{ inputs.wait-for-checks != '' }}
        with:
          list-of-checks: ${{ inputs.wait-for-checks }}

      - uses: actions/checkout@v7

      - name: Set up Golang
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Release package
        uses: softprops/action-gh-release@v3
        with:
          body: ${{ inputs.release-body }}
          generate_release_notes: true
          make_latest: true
