name: Release Library
on:
  workflow_call:
    inputs:
      release-body:
        required: true
        type: string

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - name: Set up Golang
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'

      - name: Get version from tag
        id: get_version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG#v}"
          if [[ "$VERSION" =~ ^([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            VERSION="${BASH_REMATCH[1]}"
          else
            VERSION="${VERSION%%-*}"  # Remove everything after '-'
            VERSION="${VERSION%%.*}"  # Remove everything after first '.'
          fi
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Release package
        uses: softprops/action-gh-release@v3
        with:
          body: ${{ inputs.release-body }}
          generate_release_notes: true
          make_latest: true
